name: CI Tiu Lanches Auth Function

on:
  pull_request:
    branches: [main]

env:  
  JAVA_VERSION: '17'  
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package
