name: CI Tiu Lanches Auth Function

on:
  push:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: 'tiulanches-auth-function'
  POM_XML_DIRECTORY: '.'    
  JAVA_VERSION: '17'
  SCM_CREDENTIALS: ${{ secrets.SCM_CREDENTIALS }}  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: 'Restore Project Dependencies Using Mvn'
      shell: bash
      run: |        
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        popd        
    
    - name: Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.POM_XML_DIRECTORY }}' 
        publish-profile: ${{ env.SCM_CREDENTIALS }}
        respect-pom-xml: true
