name: CI Tiu Lanches Auth Function

on:
  pull_request:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: 'tiulanches-auth-function'
  POM_XML_DIRECTORY: '.'    
  JAVA_VERSION: '17'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
  DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
  DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean package

  deploy:
    needs: build        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.POM_XML_DIRECTORY }}' 
        publish-profile: ${{ env.AZURE_CREDENTIALS }}
        respect-pom-xml: true
        
